In [1]:
import pandas as pd
import numpy as np
import ast

In [2]:
uid = "7229f66d-fe30-41d0-b02d-58a122bfca68"

Load the dataset

In [5]:
top_categories = pd.read_csv("./DataSources/top_category.csv")
merged_data = pd.read_csv("./DataSources/merged_data_with_cluster_and_label.csv")
m1_offers = pd.read_csv("./DataSources/M1_offers.csv")
m1_offers

,offer_id,merchant_name,Merchant_type,offer_title,Offer_amount(%),Offer,valid_from,valid_to,created_at,affiliate_partner_name,tracking_url,affiliate_offer_id,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,15,Watsons,Health and Wellness,1.5% Cashback,1.5,1.5,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-18 8:38:28,Optimise,http://clk.omgt3.com/?PID=38514&AID=2202076,38514,NaN,NaN,NaN,NaN,NaN,NaN
1,17,Adidas,NaN,3% Cashback,3,3.0,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-22 5:51:30,Optimise,https://clk.omgt3.com/?PID=36073&AID=2202076,36073,NaN,NaN,NaN,NaN,NaN,NaN
2,18,Nike,NaN,3.5% Cashback,3.5,3.5,2022-08-22 16:00:00,2023-12-31 15:59:00,2021-11-22 6:03:54,Optimise,https://clk.omgt3.com/?PID=38870&AID=2202076,38870,NaN,NaN,NaN,NaN,NaN,NaN
3,19,Puma,NaN,3% Cashback,3,3.0,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-22 6:08:46,Optimise,http://clk.omgt3.com/?PID=51181&AID=2202076,51181,NaN,NaN,NaN,NaN,NaN,NaN
4,21,Pat Pat,Fashion & Retail,7% Cashback at Pat Pat,7,7.0,2021-11-23 16:01:00,2023-12-31 15:59:00,2021-11-22 6:39:56,Optimise,https://clk.omgt3.com/?PID=39954&AID=2202076,39954,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,743,Lazada SG,Marketplace,Up to 4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:45:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
602,220,Shopee SG,Marketplace,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:54:12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
603,220,Shopee SG,Marketplace,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:56:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
604,220,Shopee SG,Marketplace,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 17:16:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
605,743,Lazada SG,Marketplace,Up to 4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 17:20:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
merged_data.head()

,Conversion ID,Advertiser,Campaign,Conversion Status,Order ID,Conversion Time,Click Time,Timezone,Currency,Original Order Value,...,Total Spend by Customer in Category,Category Wallet Share,Wallet Share by category %,Cluster,Recency_Score,Frequency_Score,Wallet_Share_Merchant_Score,Wallet_Share_Category_Score,Value_Score,ABC_Category
0,795e31f7f0d5493c87f276504585e5cf-1,Lazada SG,CPS,Pending,102277433024582x1409698861_SGAMZ-6392592678,2023-07-18 22:00:00,15/07/2023 18:07,Singapore Standard Time,SGD,2.76,...,178.92,0.060535,6.053532,0,0.004167,1.0,0.007983,0.060535,0.214537,A
1,6a97e2d3671345c4b22185140db74b70-1,Lazada SG,CPS,Pending,102277432524582x1409698861_SGAMZ-6392592678,2023-07-18 22:00:00,15/07/2023 18:07,Singapore Standard Time,SGD,2.77,...,178.92,0.060535,6.053532,0,0.004167,1.0,0.007983,0.060535,0.214537,A
2,f23a7ec4e80e4c738adad6d0679ce55f-1,Lazada SG,CPS,Pending,102277433824582x1409698861_SGAMZ-6392592678,2023-07-18 22:00:00,15/07/2023 18:07,Singapore Standard Time,SGD,2.76,...,178.92,0.060535,6.053532,0,0.004167,1.0,0.007983,0.060535,0.214537,A
3,5f56c247b7534a1a9b2ede2e55cdd76c-1,Lazada SG,CPS,Pending,102277430924582x1409698861_SGAMZ-6392592678,2023-07-18 22:00:00,15/07/2023 18:07,Singapore Standard Time,SGD,2.77,...,178.92,0.060535,6.053532,0,0.004167,1.0,0.007983,0.060535,0.214537,A
4,c30b28dcb9974fd38fa89a0d5606f761-1,Lazada SG,CPS,Pending,102277431124582x1409698861_SGAMZ-6392592678,2023-07-18 22:00:00,15/07/2023 18:07,Singapore Standard Time,SGD,2.77,...,178.92,0.060535,6.053532,0,0.004167,1.0,0.007983,0.060535,0.214537,A

In [6]:

label = merged_data.loc[merged_data["UID"] == uid, "ABC_Category"].iloc[0]
cluster = merged_data.loc[merged_data["UID"] == uid, "Cluster"].iloc[0]
print("label:", label, "cluster:", cluster)
matching_rows = top_categories[(top_categories["label"] == label) & (top_categories["cluster"] == int(cluster))]
v = matching_rows["top_categories"].iloc[0]
data_dict = ast.literal_eval(v)
data_dict

label: A cluster: 1

{"Women's Shoes and Clothing": 10,
 'Kitchen & Dining': 10,
 'Furniture & Organization': 9,
 "Kids' Shoes and Clothing": 8,
 'Watches Sunglasses Jewellery': 6,
 'Laundry & Cleaning Equipment': 1}

In [7]:
category_mapping = {
    'Beauty': ['Beauty'],
    'Electronics': ['Audio', 'Mobile & Gadgets', 'Cameras & Drones', 'Computers & Accessories', 'Electronics Accessories', 'Monitors & Printers', 'Smart Devices', 'Digital Utilities', 'Televisions & Videos', 'Digital Goods', 'Data Storage', 'Mobiles & Tablets'],
    'Entertainment': ['Gaming & Consoles', 'Media, Music & Books'],
    'Fashion & Retail': ['Fashion Accessories', 'Women Shoes', 'Women Clothes', 'Men Clothes', 'Baby & Kids Fashion', 'Women Bags', 'Muslim Fashion', 'Men Bags', 'Men Shoes', "Women's Shoes and Clothing", "Men's Shoes and Clothing", "Kids' Shoes and Clothing"],
    'Health and Wellness': ['Health'],
    'Hobbies': ['Hobbies & Collections', 'Toys & Games'],
    'Home Improvement/Furniture': ['Home & Living', 'Home Appliances', 'Kitchen & Dining', 'Lighting & DÃ©cor', 'Small Appliances', 'Household Supplies', 'Bedding & Bath', 'Outdoor & Garden', 'Furniture & Organization', 'Tools & Home Improvement', 'Laundry & Cleaning Equipment', 'Large Appliances'],
    'Jewelry & Timepieces': ['Watches', 'Watches Sunglasses Jewellery'],
    'Miscellaneous': ['Automobiles', 'Pets', 'Mom & Baby', 'Books & Magazines', 'Stationery', 'Tickets, Vouchers & Services', 'Motorcycles', 'Free Sample (Flexi Combo)', 'Pet Supplies', 'Mother & Baby', 'Stationery, Craft & Gift Cards', 'Motors', 'Surprise Box', 'Telco', 'Stationery & Craft', 'Local Service', 'Services'],
    'Sports and Fitness': ['Sports & Outdoors', 'Sports Shoes and Clothing'],
    'Supermarkets': ['Food & Beverage', 'Groceries'],
    'Travel': ['Travel & Luggage', 'Bags and Travel'],
    'Retailers': [],
    'Marketplace': [],
    'Cafe': [],
    'Finance and Banking': [],
    'Department Stores': [],
    'Visa Generic': [],
    'Real Estate': [],
    'Restaurants': []
}

In [27]:
m1_offers["category"] = m1_offers["Merchant_type"]
del m1_offers["Merchant_type"]

KeyError: 'Merchant_type'

In [15]:
cats = m1_offers["category"].fillna("Other")
cats

0      Health and Wellness
1                    Other
2                    Other
3                    Other
4         Fashion & Retail
              ...
601            Marketplace
602            Marketplace
603            Marketplace
604            Marketplace
605            Marketplace
Name: category, Length: 606, dtype: object

In [56]:
# Fill in missing values with "Others"
m1_offers["category"] = m1_offers["category"].fillna("Others")
m1_offers

,offer_id,merchant_name,offer_title,Offer_amount(%),Offer,valid_from,valid_to,created_at,affiliate_partner_name,tracking_url,affiliate_offer_id,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,category
0,15,Watsons,1.5% Cashback,1.5,1.5,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-18 8:38:28,Optimise,http://clk.omgt3.com/?PID=38514&AID=2202076,38514,NaN,NaN,NaN,NaN,NaN,NaN,Health and Wellness
1,17,Adidas,3% Cashback,3,3.0,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-22 5:51:30,Optimise,https://clk.omgt3.com/?PID=36073&AID=2202076,36073,NaN,NaN,NaN,NaN,NaN,NaN,Others
2,18,Nike,3.5% Cashback,3.5,3.5,2022-08-22 16:00:00,2023-12-31 15:59:00,2021-11-22 6:03:54,Optimise,https://clk.omgt3.com/?PID=38870&AID=2202076,38870,NaN,NaN,NaN,NaN,NaN,NaN,Others
3,19,Puma,3% Cashback,3,3.0,2021-11-23 16:01:00,2024-06-30 15:59:59,2021-11-22 6:08:46,Optimise,http://clk.omgt3.com/?PID=51181&AID=2202076,51181,NaN,NaN,NaN,NaN,NaN,NaN,Others
4,21,Pat Pat,7% Cashback at Pat Pat,7,7.0,2021-11-23 16:01:00,2023-12-31 15:59:00,2021-11-22 6:39:56,Optimise,https://clk.omgt3.com/?PID=39954&AID=2202076,39954,NaN,NaN,NaN,NaN,NaN,NaN,Fashion & Retail
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
601,743,Lazada SG,Up to 4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:45:27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marketplace
602,220,Shopee SG,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:54:12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marketplace
603,220,Shopee SG,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 16:56:08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marketplace
604,220,Shopee SG,Up to 4.4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 17:16:58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marketplace
605,743,Lazada SG,Up to 4% Cashback,NaN,NaN,NaN,NaN,2023-10-09 17:20:05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Marketplace

In [24]:
# Categories with frequencies
feq_cats = {
    "Women's Shoes and Clothing": 10,
    'Kitchen & Diniang': 10,
    'Furniture & Organization': 9,
    "Kids' Shoes and Clothing": 8,
    'Watches Sunglasses Jewellery': 6,
    'Laundry & Cleaning Equipment': 1
}

# Mapping specific categories to their broad categories
mapped_feq_cats = {}

# Loop through the feq_cats to find and map them to their broad category
for specific_cat, frequency in feq_cats.items():
    for broad_cat, specific_cats in category_mapping.items():
        if specific_cat in specific_cats:
            mapped_feq_cats[broad_cat] = mapped_feq_cats.get(broad_cat, 0) + frequency

mapped_feq_cats

{'Fashion & Retail': 18,
 'Home Improvement/Furniture': 20,
 'Jewelry & Timepieces': 6}

In [61]:
keys = {'Fashion & Retail': 18, 'Home Improvement/Furniture': 20, 'Jewelry & Timepieces': 6,"Health and Wellness": 1 }.keys()
filtered_offers = m1_offers[m1_offers['category'].isin(keys)]
selected_columns = filtered_offers[["merchant_name", "offer_title", "category", "Offer_amount(%)", "affiliate_partner_name"]]
selected_columns

,merchant_name,offer_title,category,Offer_amount(%),affiliate_partner_name
0,Watsons,1.5% Cashback,Health and Wellness,1.5,Optimise
4,Pat Pat,7% Cashback at Pat Pat,Fashion & Retail,7,Optimise
7,Under Armour,4% Cashback,Fashion & Retail,4,Optimise
21,Pedro Shoes,2% Cashback at Pedro Shoes,Fashion & Retail,2,Optimise
26,Pat Pat,5% Cashback at PatPat,Fashion & Retail,5,Optimise
70,Pat Pat,4.2% Cashback,Fashion & Retail,4.2,Involve Asia
76,Pat Pat,4.2% Cashback,Fashion & Retail,4.2,Involve Asia
77,Pat Pat,3% Cashback,Fashion & Retail,3,Involve Asia
78,Pat Pat,3% Cashback,Fashion & Retail,3,Involve Asia
226,Watsons,1.5% Cashback,Health and Wellness,NaN,NaN
227,Watsons,1.5% Cashback,Health and Wellness,NaN,NaN
267,Skechers,5% Cashback,Fashion & Retail,NaN,NaN
408,Cotton On,Up to 4.6% Cashback,Fashion & Retail,NaN,NaN
439,Pat Pat,Up to 3% Cashback,Fashion & Retail,NaN,NaN
456,Watsons,1.5% Cashback,Health and Wellness,NaN,NaN
563,Watsons,1.5% Cashback,Health and Wellness,NaN,NaN
567,Pat Pat,Up to 3% Cashback,Fashion & Retail,NaN,NaN
570,The Luxury Closet,6% Cashback,Fashion & Retail,NaN,NaN

In [63]:
selected_columns.category.value_counts()

category
Fashion & Retail       13
Health and Wellness     5
Name: count, dtype: int64

In [57]:
len(filtered_offers)

18

In [55]:
m1_offers.category.value_counts()

category
Marketplace            316
Supermarkets           138
Others                  98
Fashion & Retail        13
Travel                  13
Retailers                7
Sports and Fitness       6
Health and Wellness      5
Electronics              5
Beauty                   3
Cafe                     1
Entertainment            1
Name: count, dtype: int64

In [53]:
# # duplicate a row and change the category column value
# row_to_duplicate = m1_offers.iloc[0].copy()
# row_to_duplicate['category'] = 'Health and Wellness'
# row_added = pd.concat([m1_offers, pd.DataFrame([row_to_duplicate])], ignore_index=True)
# row_added 

# # row_to_duplicate

## Collab Models

In [ ]:
# Version 1
import pandas as pd
from datetime import datetime
from sklearn.metrics.pairwise import cosine_similarity

#changed the file path
df = pd.read_csv("s3://pulse-id-data/Raw_Data/M1/Final_Test.csv", encoding='latin1')
merged_df = pd.read_csv("Dataset_V1.csv")

# Load the offer dataset from the CSV file
offer_df = pd.read_csv("M1_offers.csv")

#Changed
# Drop rows with NaN values
merged_df = merged_df.dropna()


# Calculate user-user similarity based on RFAT and wallet share by category
def calculate_user_similarity(merged_df):
    user_features = merged_df.drop(columns=['UID', 'Conversion Time'])  # Exclude UID and Conversion Time
    user_similarity_matrix = cosine_similarity(user_features)
    return user_similarity_matrix

# Example: Get top N similar users for a given user
def get_top_similar_users(merged_df, user_similarity_matrix, user_id, n=5):
    if user_id not in merged_df['UID'].values:
        print(f"User ID {user_id} does not exist. Using default recommendations.")
        return []
    user_index = merged_df.index[merged_df['UID'] == user_id][0]
    similar_users = user_similarity_matrix[user_index].argsort()[::-1][1:n+1]
    return similar_users

# Example: Aggregate top categories from similar users
def aggregate_top_categories_from_similar_users(merged_df, similar_users, n=10):
    category_columns = [col for col in merged_df.columns if col not in ['UID', 'Conversion Time', 'Recency', 'Frequency', 'AOV', 'Total Spending','Unique Category Counts']]
    top_categories = merged_df.iloc[similar_users][category_columns].sum().nlargest(n).index.tolist()
    return top_categories

# Example: Recommend top categories for a given user
def recommend_top_categories(merged_df, user_similarity_matrix, user_id, n=10):
    similar_users = get_top_similar_users(merged_df, user_similarity_matrix, user_id)
    if len(similar_users) == 0:  # Check if no similar users were found
        return default_recommendations(df), []  # Fallback to default recommendations and empty offer categories
    top_categories = aggregate_top_categories_from_similar_users(merged_df, similar_users, n)
    return top_categories

# Example: Default recommendations for new users
def default_recommendations(df, n=10):
    # Provide default recommendations based on popular or trending categories
    # Example: Default recommendations for new users
    # Group by category and sum the order value to find the most purchased categories
    top_categories = df.groupby('ex3/category')['Order Value'].sum().nlargest(n).index.tolist()
    return top_categories

# Example: Format output nicely
def format_output(user_id, top_categories):
    output = f"Top {len(top_categories)} categories for user: {user_id}"
    for i, category in enumerate(top_categories, start=1):
        output += f"\n{i}. {category}"
    return output

#Changed
# Define the mapping between transaction sub-categories and offer main categories
category_mapping = {
    'Beauty': ['Beauty'],
    'Electronics': ['Audio', 'Electronics', 'Mobile & Gadgets', 'Cameras & Drones', 'Computers & Accessories', 'Electronics Accessories', 'Monitors & Printers', 'Smart Devices', 'Digital Utilities', 'Televisions & Videos', 'Digital Goods', 'Data Storage', 'Mobiles & Tablets'],
    'Entertainment': ['Gaming & Consoles', 'Media, Music & Books', 'Entertainment'],
    'Fashion & Retail': ['Fashion Accessories', 'Fashion & Retail', 'Women Shoes', 'Women Clothes', 'Men Clothes', 'Baby & Kids Fashion', 'Women Bags', 'Muslim Fashion', 'Men Bags', 'Men Shoes', "Women's Shoes and Clothing", "Men's Shoes and Clothing", "Kids' Shoes and Clothing"],
    'Health and Wellness': ['Health', 'Health and Wellness'],
    'Hobbies': ['Hobbies & Collections', 'Hobbies', 'Toys & Games'],
    'Home Improvement/Furniture': ['Home & Living', 'Home Improvement/Furniture', 'Home Appliances', 'Kitchen & Dining', 'Lighting & DÃ©cor', 'Small Appliances', 'Household Supplies', 'Bedding & Bath', 'Outdoor & Garden', 'Furniture & Organization', 'Tools & Home Improvement', 'Laundry & Cleaning Equipment', 'Large Appliances'],
    'Jewelry & Timepieces': ['Watches', 'Jewelry & Timepiece', 'Watches Sunglasses Jewellery'],
    'Miscellaneous': ['Automobiles','Miscellaneous', 'Pets', 'Mom & Baby', 'Books & Magazines', 'Stationery', 'Tickets, Vouchers & Services', 'Motorcycles', 'Free Sample (Flexi Combo)', 'Pet Supplies', 'Mother & Baby', 'Stationery, Craft & Gift Cards', 'Motors', 'Surprise Box', 'Telco', 'Stationery & Craft', 'Local Service', 'Services'],
    'Sports and Fitness': ['Sports & Outdoors', 'Sports and Fitness', 'Sports Shoes and Clothing'],
    'Supermarkets': ['Food & Beverage', 'Supermarkets','Groceries'],
    'Travel': ['Travel & Luggage', 'Travel','Bags and Travel'],
    'Retailers': ['Retailers'],
    'Marketplace': ['Marketplace'],
    'Cafe': ['Cafe'],
    'Finance and Banking': ['Finance and Banking'],
    'Department Stores': ['Department Stores'],
    'Visa Generic': ['VISA Generic'],
    'VISA Generic': ['VISA Generic'],
    'Real Estate': ['Real Estate'],
    'Restaurants': ['Restaurants']
}

# Map transaction sub-categories to offer main categories
def map_to_offer_category(sub_categories):
    offer_categories = set()
    for sub_category in sub_categories:
        for offer_category, mapped_sub_categories in category_mapping.items():
            if sub_category in mapped_sub_categories:
                offer_categories.add(offer_category)
    return list(offer_categories)

# Changed Function
# Map top categories to offer categories
def map_top_categories_to_offers(top_categories):
    offer_categories = []
    for category in top_categories:
        mapped_categories = map_to_offer_category([category])
        if mapped_categories:  # Check if the list is not empty
            offer_categories.append(mapped_categories[0])
        else: 
            print(mapped_categories, category)
    return offer_categories


# Example: Get top category recommendations for a user using collaborative filtering
def get_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df):
    if user_id not in merged_df['UID'].values:
        print(f"User ID {user_id} does not exist. Using default recommendations.")
        default_categories = default_recommendations(df)
        default_offer_categories = map_top_categories_to_offers(default_categories)
        return default_categories, default_offer_categories
    top_categories_collaborative = recommend_top_categories(merged_df, user_similarity_matrix, user_id)
    offer_categories_collaborative = map_top_categories_to_offers(top_categories_collaborative)
    return top_categories_collaborative, offer_categories_collaborative

# Define function to recommend offers for each offer category
def recommend_offers_for_category(offer_df, offer_category):
    # Filter offers based on the "Merchant_type" column to match the offer category
    matching_offers = offer_df[offer_df['Merchant_type'] == offer_category]
    return matching_offers

# Define function to recommend offers for each offer category
def recommend_offers_for_categories(offer_df, offer_categories):
    recommended_offers = {}
    unique_categories = set(offer_categories)  # Use a set to remove duplicates
    for category in unique_categories:
        recommended_offers[category] = recommend_offers_for_category(offer_df, category)
    return recommended_offers

# Example: Print top and offer categories for a user
def print_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df):
    top_categories, offer_categories = get_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df)
    
    print(f"Top categories for user {user_id}:")
    for i, category in enumerate(top_categories, start=1):
        print(f"{i}. {category}")

    seen_categories = set()
    ordered_categories = []  # List to maintain order of first appearance
    print("\nOffer categories:")
    for category in offer_categories:
        if category not in seen_categories:  # Check if category has been printed already
            seen_categories.add(category)
            ordered_categories.append(category)  # Add category to the ordered list
            print(f"{len(ordered_categories)}. {category}")

    recommended_offers = recommend_offers_for_categories(offer_df, seen_categories)  # Pass the unique set of categories

    print(f"\nOffers we recommend for user {user_id}:")
    for i, category in enumerate(ordered_categories, start=1):  # Use ordered_categories to maintain the order
        print(f"\n{i}. {category}")
        if not recommended_offers[category].empty:
            print(recommended_offers[category][['offer_id', 'merchant_name', 'offer_title', 'Offer_amount(%)']].to_string(index=False))
        else:
            print("No offers available for this category.")
         
     #Changed -Added list of offers
        # Read the M1_offers.csv file
    offer_df = pd.read_csv("M1_offers.csv")

    # Offer IDs provided
    offer_ids = [15, 699, 627, 10, 20, 138, 21]

    # Offer categories
    offer_categories = offer_categories

    # Filter the offer DataFrame for the provided offer IDs
    filtered_offers = offer_df[offer_df['offer_id'].isin(offer_ids)]

    # Extract the relevant Merchant_type for the filtered offers
    merchant_types = filtered_offers.set_index('offer_id')['Merchant_type'].to_dict()

    # Initialize lists to store the matching and non-matching offer IDs
    matching_offer_ids = []
    non_matching_offer_ids = []

    # Match each Merchant_type with the offer categories
    for offer_category in offer_categories:
        for offer_id, merchant_type in merchant_types.items():
            if merchant_type == offer_category:
                matching_offer_ids.append(offer_id)

    # Get non-matching offer IDs
    non_matching_offer_ids = [offer_id for offer_id in offer_ids if offer_id not in matching_offer_ids]

    # Print matching offer IDs first, then non-matching ones
    print("Matching Offer IDs:", matching_offer_ids)
    print("Non-Matching Offer IDs:", non_matching_offer_ids)
    # Merge matching_offer_ids and non_matching_offer_ids
    merged_offer_ids = matching_offer_ids + non_matching_offer_ids
    print('Merged offer IDs list')
    print(merged_offer_ids)





# Example: Get top category recommendations for a user
#003d363e-5e74-4bd9-9b7f-77d1ddf0ad62 Unique Category Counts 1
#05e3cacf-ce64-488f-9f42-f8c1c0a78fd5 Unique Category Counts 22
#009caacf-c094-4b84-adde-424c584b0b33 Unique Category Counts 3
#06034ff3-ba22-4b1c-9f09-6253c35e7658 Unique Category Counts 4
#01 New User
user_id = 'DILEEMAEXTUSERL005'
user_similarity_matrix = calculate_user_similarity(merged_df)
print_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df)

In [ ]:
# Version 2
import pandas as pd
from datetime import datetime
from sklearn.metrics.pairwise import cosine_similarity

#Changed the file path
df = pd.read_csv("s3://pulse-id-data/Raw_Data/M1/Final_Test.csv", encoding='latin1')
merged_df = pd.read_csv("Dataset_V2.csv")

# Load the offer dataset from the CSV file
offer_df = pd.read_csv("M1_offers.csv")

#Changed
# Drop rows with NaN values
merged_df = merged_df.dropna()

# Calculate user-user similarity based on RFAT and wallet share by category
def calculate_user_similarity(merged_df):
    user_features = merged_df.drop(columns=['UID', 'Conversion Time'])  # Exclude UID and Conversion Time
    user_similarity_matrix = cosine_similarity(user_features)
    return user_similarity_matrix

# Example: Get top N similar users for a given user
def get_top_similar_users(merged_df, user_similarity_matrix, user_id, n=5):
    if user_id not in merged_df['UID'].values:
        print(f"User ID {user_id} does not exist. Using default recommendations.")
        return []
    user_index = merged_df.index[merged_df['UID'] == user_id][0]
    similar_users = user_similarity_matrix[user_index].argsort()[::-1][1:n+1]
    return similar_users

# Example: Aggregate top categories from similar users
def aggregate_top_categories_from_similar_users(merged_df, similar_users, n=10):
    category_columns = [col for col in merged_df.columns if col not in ['UID', 'Conversion Time', 'Recency', 'Frequency', 'AOV', 'Total Spending','Unique Category Counts']]
    top_categories = merged_df.iloc[similar_users][category_columns].sum().nlargest(n).index.tolist()
    return top_categories

# Example: Recommend top categories for a given user
def recommend_top_categories(merged_df, user_similarity_matrix, user_id, n=10):
    similar_users = get_top_similar_users(merged_df, user_similarity_matrix, user_id)
    if len(similar_users) == 0:  # Check if no similar users were found
        return default_recommendations(merged_df), []  # Fallback to default recommendations and empty offer categories
    top_categories = aggregate_top_categories_from_similar_users(merged_df, similar_users, n)
    return top_categories

# Example: Default recommendations for new users based on frequency
def default_recommendations(df, n=10):
    # Provide default recommendations based on popular or trending categories using frequency
    # Group by category and count the occurrences of each UID within each category
    top_categories = df.groupby('ex3/category').size().nlargest(n).index.tolist()
    return top_categories

# Example: Format output nicely
def format_output(user_id, top_categories):
    output = f"Top {len(top_categories)} categories for user: {user_id}"
    for i, category in enumerate(top_categories, start=1):
        output += f"\n{i}. {category}"
    return output


#Changed
# Define the mapping between transaction sub-categories and offer main categories
category_mapping = {
    'Beauty': ['Beauty'],
    'Electronics': ['Audio', 'Electronics', 'Mobile & Gadgets', 'Cameras & Drones', 'Computers & Accessories', 'Electronics Accessories', 'Monitors & Printers', 'Smart Devices', 'Digital Utilities', 'Televisions & Videos', 'Digital Goods', 'Data Storage', 'Mobiles & Tablets'],
    'Entertainment': ['Gaming & Consoles', 'Media, Music & Books', 'Entertainment'],
    'Fashion & Retail': ['Fashion Accessories', 'Fashion & Retail', 'Women Shoes', 'Women Clothes', 'Men Clothes', 'Baby & Kids Fashion', 'Women Bags', 'Muslim Fashion', 'Men Bags', 'Men Shoes', "Women's Shoes and Clothing", "Men's Shoes and Clothing", "Kids' Shoes and Clothing"],
    'Health and Wellness': ['Health', 'Health and Wellness'],
    'Hobbies': ['Hobbies & Collections', 'Hobbies', 'Toys & Games'],
    'Home Improvement/Furniture': ['Home & Living', 'Home Improvement/Furniture', 'Home Appliances', 'Kitchen & Dining', 'Lighting & DÃ©cor', 'Small Appliances', 'Household Supplies', 'Bedding & Bath', 'Outdoor & Garden', 'Furniture & Organization', 'Tools & Home Improvement', 'Laundry & Cleaning Equipment', 'Large Appliances'],
    'Jewelry & Timepieces': ['Watches', 'Jewelry & Timepiece', 'Watches Sunglasses Jewellery'],
    'Miscellaneous': ['Automobiles','Miscellaneous', 'Pets', 'Mom & Baby', 'Books & Magazines', 'Stationery', 'Tickets, Vouchers & Services', 'Motorcycles', 'Free Sample (Flexi Combo)', 'Pet Supplies', 'Mother & Baby', 'Stationery, Craft & Gift Cards', 'Motors', 'Surprise Box', 'Telco', 'Stationery & Craft', 'Local Service', 'Services'],
    'Sports and Fitness': ['Sports & Outdoors', 'Sports and Fitness', 'Sports Shoes and Clothing'],
    'Supermarkets': ['Food & Beverage', 'Supermarkets','Groceries'],
    'Travel': ['Travel & Luggage', 'Travel','Bags and Travel'],
    'Retailers': ['Retailers'],
    'Marketplace': ['Marketplace'],
    'Cafe': ['Cafe'],
    'Finance and Banking': ['Finance and Banking'],
    'Department Stores': ['Department Stores'],
    'Visa Generic': ['VISA Generic'],
    'VISA Generic': ['VISA Generic'],
    'Real Estate': ['Real Estate'],
    'Restaurants': ['Restaurants']
}

# Map transaction sub-categories to offer main categories
def map_to_offer_category(sub_categories):
    offer_categories = set()
    for sub_category in sub_categories:
        for offer_category, mapped_sub_categories in category_mapping.items():
            if sub_category in mapped_sub_categories:
                offer_categories.add(offer_category)
    return list(offer_categories)


#Changed Code
# Map top categories to offer categories
def map_top_categories_to_offers(top_categories):
    offer_categories = []
    for category in top_categories:
        mapped_categories = map_to_offer_category([category])
        if mapped_categories:  # Check if the list is not empty
            offer_categories.append(mapped_categories[0])
        else: 
            print(mapped_categories, category)
    return offer_categories


# Example: Get top category recommendations for a user using collaborative filtering
def get_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df):
    if user_id not in merged_df['UID'].values:
        print(f"User ID {user_id} does not exist. Using default recommendations.")
        default_categories = default_recommendations(df)
        default_offer_categories = map_top_categories_to_offers(default_categories)
        return default_categories, default_offer_categories
    top_categories_collaborative = recommend_top_categories(merged_df, user_similarity_matrix, user_id)
    offer_categories_collaborative = map_top_categories_to_offers(top_categories_collaborative)
    return top_categories_collaborative, offer_categories_collaborative

# Define function to recommend offers for each offer category
def recommend_offers_for_category(offer_df, offer_category):
    # Filter offers based on the "Merchant_type" column to match the offer category
    matching_offers = offer_df[offer_df['Merchant_type'] == offer_category]
    return matching_offers

# Define function to recommend offers for each offer category
def recommend_offers_for_categories(offer_df, offer_categories):
    recommended_offers = {}
    for category in offer_categories:
        recommended_offers[category] = recommend_offers_for_category(offer_df, category)
    return recommended_offers

# Example: Print top and offer categories for a user
def print_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df):
    top_categories, offer_categories = get_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df)
    
    print(f"Top categories for user {user_id}:")
    for i, category in enumerate(top_categories, start=1):
        print(f"{i}. {category}")

    print("\nOffer categories:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"{i}. {category}")

    recommended_offers = recommend_offers_for_categories(offer_df, offer_categories)

    print(f"\nOffers we recommend for user {user_id}:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"\n{i}. {category}")
        if not recommended_offers[category].empty:
            print(recommended_offers[category][['offer_id', 'merchant_name', 'offer_title', 'Offer_amount(%)']].to_string(index=False))
        else:
            print("No offers available for this category.")


    #Changed -Added - list of offers
        # Read the M1_offers.csv file
    offer_df = pd.read_csv("M1_offers.csv")

    # Offer IDs provided
    offer_ids = [15, 699, 627, 10, 20, 138, 21]

    # Offer categories
    offer_categories = offer_categories

    # Filter the offer DataFrame for the provided offer IDs
    filtered_offers = offer_df[offer_df['offer_id'].isin(offer_ids)]

    # Extract the relevant Merchant_type for the filtered offers
    merchant_types = filtered_offers.set_index('offer_id')['Merchant_type'].to_dict()

    # Initialize lists to store the matching and non-matching offer IDs
    matching_offer_ids = []
    non_matching_offer_ids = []

    # Match each Merchant_type with the offer categories
    for offer_category in offer_categories:
        for offer_id, merchant_type in merchant_types.items():
            if merchant_type == offer_category:
                matching_offer_ids.append(offer_id)

    # Get non-matching offer IDs
    non_matching_offer_ids = [offer_id for offer_id in offer_ids if offer_id not in matching_offer_ids]

    # Print matching offer IDs first, then non-matching ones
    print("Matching Offer IDs:", matching_offer_ids)
    print("Non-Matching Offer IDs:", non_matching_offer_ids)
    # Merge matching_offer_ids and non_matching_offer_ids
    merged_offer_ids = matching_offer_ids + non_matching_offer_ids
    print('Merged offer IDs list')
    print(merged_offer_ids)
    


# Example: Get top category recommendations for a user
#003d363e-5e74-4bd9-9b7f-77d1ddf0ad62 Unique Category Counts 1
#05e3cacf-ce64-488f-9f42-f8c1c0a78fd5 Unique Category Counts 22
#009caacf-c094-4b84-adde-424c584b0b33 Unique Category Counts 3
#06034ff3-ba22-4b1c-9f09-6253c35e7658 Unique Category Counts 4
#01 New User
user_id = '009caacf-c094-4b84-adde-424c584b0b33'
user_similarity_matrix = calculate_user_similarity(merged_df)
print_top_and_offer_categories(merged_df, user_similarity_matrix, user_id, offer_df)

## Content

In [7]:
# Version 1
import pandas as pd
from datetime import datetime
from sklearn.metrics.pairwise import cosine_similarity


#changed the file path

#changed the file path
df = pd.read_csv("./DataSources/Final_Test.csv", encoding='latin1')
merged_df = pd.read_csv("./DataSources/Dataset_V2 (1).csv")
offer_df = pd.read_csv("./DataSources/M1_offers (2).csv")
#changed
# Drop rows with NaN values
merged_df = merged_df.dropna()


# Calculate user-user similarity based on RFAT and wallet share by category
def calculate_user_similarity(merged_df):
    user_features = merged_df.drop(columns=['UID', 'Conversion Time'])  # Exclude UID and Conversion Time
    user_similarity_matrix = cosine_similarity(user_features)
    return user_similarity_matrix

# Example: Aggregate top categories from user's historical data
def aggregate_top_categories_from_user_data(user_data, n=10):
    user_categories = user_data.drop(columns=['UID', 'Conversion Time', 'Recency', 'Frequency', 'AOV', 'Total Spending','Unique Category Counts']).iloc[0]
    top_categories = user_categories.nlargest(n).index.tolist()
    return top_categories

# Example: Recommend top categories for a given user using content-based filtering
def recommend_top_categories_content_based(merged_df, user_id, n=10):
    user_data = merged_df[merged_df['UID'] == user_id]
    if user_data.empty:  # Check if user has no historical data
        return default_recommendations(df, n)  # Fallback to default recommendations
    top_categories = aggregate_top_categories_from_user_data(user_data, n)
    return top_categories

# Example: Default recommendations for new users
def default_recommendations(df, n=10):
    # Provide default recommendations based on popular or trending categories
    # Example: Default recommendations for new users
    # Group by category and sum the order value to find the most purchased categories
    top_categories = df.groupby('ex3/category')['Order Value'].sum().nlargest(n).index.tolist()
    return top_categories




#Changed
# Define the mapping between transaction sub-categories and offer main categories
category_mapping = {
    'Beauty': ['Beauty'],
    'Electronics': ['Audio', 'Electronics', 'Mobile & Gadgets', 'Cameras & Drones', 'Computers & Accessories', 'Electronics Accessories', 'Monitors & Printers', 'Smart Devices', 'Digital Utilities', 'Televisions & Videos', 'Digital Goods', 'Data Storage', 'Mobiles & Tablets'],
    'Entertainment': ['Gaming & Consoles', 'Media, Music & Books', 'Entertainment'],
    'Fashion & Retail': ['Fashion Accessories', 'Fashion & Retail', 'Women Shoes', 'Women Clothes', 'Men Clothes', 'Baby & Kids Fashion', 'Women Bags', 'Muslim Fashion', 'Men Bags', 'Men Shoes', "Women's Shoes and Clothing", "Men's Shoes and Clothing", "Kids' Shoes and Clothing"],
    'Health and Wellness': ['Health', 'Health and Wellness'],
    'Hobbies': ['Hobbies & Collections', 'Hobbies', 'Toys & Games'],
    'Home Improvement/Furniture': ['Home & Living', 'Home Improvement/Furniture', 'Home Appliances', 'Kitchen & Dining', 'Lighting & DÃ©cor', 'Small Appliances', 'Household Supplies', 'Bedding & Bath', 'Outdoor & Garden', 'Furniture & Organization', 'Tools & Home Improvement', 'Laundry & Cleaning Equipment', 'Large Appliances'],
    'Jewelry & Timepieces': ['Watches', 'Jewelry & Timepiece', 'Watches Sunglasses Jewellery'],
    'Miscellaneous': ['Automobiles','Miscellaneous', 'Pets', 'Mom & Baby', 'Books & Magazines', 'Stationery', 'Tickets, Vouchers & Services', 'Motorcycles', 'Free Sample (Flexi Combo)', 'Pet Supplies', 'Mother & Baby', 'Stationery, Craft & Gift Cards', 'Motors', 'Surprise Box', 'Telco', 'Stationery & Craft', 'Local Service', 'Services'],
    'Sports and Fitness': ['Sports & Outdoors', 'Sports and Fitness', 'Sports Shoes and Clothing'],
    'Supermarkets': ['Food & Beverage', 'Supermarkets','Groceries'],
    'Travel': ['Travel & Luggage', 'Travel','Bags and Travel'],
    'Retailers': ['Retailers'],
    'Marketplace': ['Marketplace'],
    'Cafe': ['Cafe'],
    'Finance and Banking': ['Finance and Banking'],
    'Department Stores': ['Department Stores'],
    'Visa Generic': ['VISA Generic'],
    'VISA Generic': ['VISA Generic'],
    'Real Estate': ['Real Estate'],
    'Restaurants': ['Restaurants']
}


# Map transaction sub-categories to offer main categories
def map_to_offer_category(sub_categories):
    offer_categories = set()
    for sub_category in sub_categories:
        for offer_category, mapped_sub_categories in category_mapping.items():
            if sub_category in mapped_sub_categories:
                offer_categories.add(offer_category)
    return list(offer_categories)

#Changed
# Map top categories to offer categories
def map_top_categories_to_offers(top_categories):
    offer_categories = []
    for category in top_categories:
        mapped_categories = map_to_offer_category([category])
        if mapped_categories:  # Check if the list is not empty
            offer_categories.append(mapped_categories[0])
        else: 
            print(mapped_categories, category)
    return offer_categories

# Define function to recommend offers for each offer category
def recommend_offers_for_category(offer_df, offer_category):
    # Filter offers based on the "Merchant_type" column to match the offer category
    matching_offers = offer_df[offer_df['Merchant_type'] == offer_category]
    return matching_offers

# Define function to recommend offers for each offer category
def recommend_offers_for_categories(offer_df, offer_categories):
    recommended_offers = {}
    for category in offer_categories:
        recommended_offers[category] = recommend_offers_for_category(offer_df, category)
    return recommended_offers

# Example: Print top and offer categories for a user
def print_top_and_offer_categories(merged_df, user_id, offer_df):
    top_categories = recommend_top_categories_content_based(merged_df, user_id)
    
    print(f"Top categories for user {user_id}:")
    for i, category in enumerate(top_categories, start=1):
        print(f"{i}. {category}")

    offer_categories = map_top_categories_to_offers(top_categories)

    print("\nOffer categories:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"{i}. {category}")

    recommended_offers = recommend_offers_for_categories(offer_df, offer_categories)

    print(f"\nOffers we recommend for user {user_id}:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"\n{i}. {category}")
        if not recommended_offers[category].empty:
            print(recommended_offers[category][['offer_id', 'merchant_name', 'offer_title', 'Offer_amount(%)']].to_string(index=False))
        else:
            print("No offers available for this category.")

     #Changed- added list of offers
    # Read the M1_offers.csv file

    # Offer IDs provided
    offer_ids = [7, 699,23, 627, 10, 20]

    # Offer categories
    offer_categories = offer_categories

    # Filter the offer DataFrame for the provided offer IDs
    filtered_offers = offer_df[offer_df['offer_id'].isin(offer_ids)]

    # Extract the relevant Merchant_type for the filtered offers
    merchant_types = filtered_offers.set_index('offer_id')['Merchant_type'].to_dict()

    # Initialize lists to store the matching and non-matching offer IDs
    matching_offer_ids = []
    non_matching_offer_ids = []

    # Match each Merchant_type with the offer categories
    for offer_category in offer_categories:
        for offer_id, merchant_type in merchant_types.items():
            if merchant_type == offer_category:
                matching_offer_ids.append(offer_id)

    # Get non-matching offer IDs
    non_matching_offer_ids = [offer_id for offer_id in offer_ids if offer_id not in matching_offer_ids]

    # Print matching offer IDs first, then non-matching ones
    print("Matching Offer IDs:", matching_offer_ids)
    print("Non-Matching Offer IDs:", non_matching_offer_ids)
    # Merge matching_offer_ids and non_matching_offer_ids
    merged_offer_ids = matching_offer_ids + non_matching_offer_ids
    print('Merged offer IDs list')
    print(merged_offer_ids)
                 

# Example: Get top category recommendations for a user
#003d363e-5e74-4bd9-9b7f-77d1ddf0ad62 Unique Category Counts 1
#05e3cacf-ce64-488f-9f42-f8c1c0a78fd5 Unique Category Counts 22
#009caacf-c094-4b84-adde-424c584b0b33 Unique Category Counts 3
#06034ff3-ba22-4b1c-9f09-6253c35e7658 Unique Category Counts 4
#01 New User
user_id = 'DILEEMAEXTUSERL006'
print_top_and_offer_categories(merged_df, user_id, offer_df)

Top categories for user DILEEMAEXTUSERL006:
1. Electronics
2. Restaurants
3. Fashion & Retail
4. Audio
5. Automobiles
6. Baby & Kids Fashion
7. Bags and Travel
8. Beauty
9. Bedding & Bath
10. Books & Magazines

Offer categories:
1. Electronics
2. Restaurants
3. Fashion & Retail
4. Electronics
5. Miscellaneous
6. Fashion & Retail
7. Travel
8. Beauty
9. Home Improvement/Furniture
10. Miscellaneous

Offers we recommend for user DILEEMAEXTUSERL006:

1. Electronics
 offer_id merchant_name   offer_title Offer_amount(%)
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      713          ASUS 2.3% Cashback             NaN

2. Restaurants
 offer_id merchant_name           offer_title Offer_amount(%)
     7826         Prada Get USDÂ 5.00 Cashback               5

3. Fashion & Retail
 offer_id     merchant_name                offer_title Offer_amount(%)
       21          Pat Pat      7% Cashback at Pat Pat               7
       38     Under Armour                 4% Cashback               4
      627      Pedro Shoes  2% Cashback at Pedro Shoes               2
      689          Pat Pat       5% Cashback at PatPat               5
      747          Pat Pat               4.2% Cashback             4.2
      762          Pat Pat               4.2% Cashback             4.2
      765          Pat Pat                 3% Cashback               3
      766          Pat Pat                 3% Cashback               3
      714          Skechers                5% Cashback             NaN
      711         Cotton On        Up to 4.6% Cashback             NaN
      766          Pat Pat           Up to 3% Cashback             NaN
      766          Pat Pat           Up to 3% Cashback             NaN
      769 The Luxury Closet               6% Cashback              NaN
     7788           Nolimit      Get AUDÂ 5.00 Cashback               5
     7803           Nolimit      Get AUDÂ 5.00 Cashback               5
     7816           Nolimit     Get USDÂ 10.00 Cashback              10
     7820           Nolimit     Get USDÂ 10.00 Cashback              10
     7817           Nolimit     Get USDÂ 10.00 Cashback              10
     7839           Nolimit     Get USDÂ 10.00 Cashback              10
     7843           Nolimit     Get USDÂ 10.00 Cashback              10
     7860           Nolimit    Get USDÂ 100.00 Cashback             100

4. Electronics
 offer_id merchant_name   offer_title Offer_amount(%)
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      138    Samsung SG 1.5% Cashback             NaN
      713          ASUS 2.3% Cashback             NaN

5. Miscellaneous
No offers available for this category.

6. Fashion & Retail
 offer_id     merchant_name                offer_title Offer_amount(%)
       21          Pat Pat      7% Cashback at Pat Pat               7
       38     Under Armour                 4% Cashback               4
      627      Pedro Shoes  2% Cashback at Pedro Shoes               2
      689          Pat Pat       5% Cashback at PatPat               5
      747          Pat Pat               4.2% Cashback             4.2
      762          Pat Pat               4.2% Cashback             4.2
      765          Pat Pat                 3% Cashback               3
      766          Pat Pat                 3% Cashback               3
      714          Skechers                5% Cashback             NaN
      711         Cotton On        Up to 4.6% Cashback             NaN
      766          Pat Pat           Up to 3% Cashback             NaN
      766          Pat Pat           Up to 3% Cashback             NaN
      769 The Luxury Closet               6% Cashback              NaN
     7788           Nolimit      Get AUDÂ 5.00 Cashback               5
     7803           Nolimit      Get AUDÂ 5.00 Cashback               5
     7816           Nolimit     Get USDÂ 10.00 Cashback              10
     7820           Nolimit     Get USDÂ 10.00 Cashback              10
     7817           Nolimit     Get USDÂ 10.00 Cashback              10
     7839           Nolimit     Get USDÂ 10.00 Cashback              10
     7843           Nolimit     Get USDÂ 10.00 Cashback              10
     7860           Nolimit    Get USDÂ 100.00 Cashback             100

7. Travel
 offer_id                merchant_name         offer_title Offer_amount(%)
      706                     Trip.com       4.5% Cashback             4.5
      706                     Trip.com       4.5% Cashback             NaN
      706                     Trip.com       4.5% Cashback             NaN
      706                     Trip.com       4.5% Cashback             NaN
      707                        Klook   Up to 4% Cashback             NaN
      745            Singapore Airline       0.5% Cashback             NaN
      767                       Tiqets         6% Cashback             NaN
      770 Allianz Assistnace Singapore Up to $60 Cashback              NaN
      771                        Agoda   Up to 5% cashback             NaN
      771                        Agoda   Up to 5% cashback             NaN
      771                        Agoda   Up to 5% cashback             NaN
      767                       Tiqets         6% Cashback             NaN
      770 Allianz Assistnace Singapore Up to $60 Cashback              NaN

8. Beauty
 offer_id merchant_name         offer_title Offer_amount(%)
       51       Sephora       5.5% Cashback             5.5
       51       Sephora Up to 5.5% Cashback             NaN
       51       Sephora Up to 5.5% Cashback             NaN

9. Home Improvement/Furniture
No offers available for this category.

10. Miscellaneous
No offers available for this category.
Matching Offer IDs: [627, 627]
Non-Matching Offer IDs: [7, 699, 23, 10, 20]
Merged offer IDs list
[627, 627, 7, 699, 23, 10, 20]

In [ ]:
# version 2
import pandas as pd
from datetime import datetime
from sklearn.metrics.pairwise import cosine_similarity

#Changed path
df = pd.read_csv("s3://pulse-id-data/Raw_Data/M1/Final_Test.csv", encoding='latin1')
merged_df = pd.read_csv("Dataset_V2.csv")

#Changed
# Drop rows with NaN values
merged_df = merged_df.dropna()

# Calculate user-user similarity based on RFAT and wallet share by category
def calculate_user_similarity(merged_df):
    user_features = merged_df.drop(columns=['UID', 'Conversion Time'])  # Exclude UID and Conversion Time
    user_similarity_matrix = cosine_similarity(user_features)
    return user_similarity_matrix

# Example: Aggregate top categories from user's historical data
def aggregate_top_categories_from_user_data(user_data, n=10):
    user_categories = user_data.drop(columns=['UID', 'Conversion Time', 'Recency', 'Frequency', 'AOV', 'Total Spending','Unique Category Counts']).iloc[0]
    top_categories = user_categories.nlargest(n).index.tolist()
    return top_categories

# Example: Recommend top categories for a given user using content-based filtering
def recommend_top_categories_content_based(merged_df, user_id, n=10):
    user_data = merged_df[merged_df['UID'] == user_id]
    if user_data.empty:  # Check if user has no historical data
        return default_recommendations(df, n)  # Fallback to default recommendations
    top_categories = aggregate_top_categories_from_user_data(user_data, n)
    return top_categories

# Example: Default recommendations for new users based on frequency
def default_recommendations(df, n=10):
    # Provide default recommendations based on popular or trending categories using frequency
    # Group by category and count the occurrences of each UID within each category
    top_categories = df.groupby('ex3/category').size().nlargest(n).index.tolist()
    return top_categories

# Load the offer dataset from the CSV file
offer_df = pd.read_csv("M1_offers.csv")

#Changed
# Define the mapping between transaction sub-categories and offer main categories
category_mapping = {
    'Beauty': ['Beauty'],
    'Electronics': ['Audio', 'Electronics', 'Mobile & Gadgets', 'Cameras & Drones', 'Computers & Accessories', 'Electronics Accessories', 'Monitors & Printers', 'Smart Devices', 'Digital Utilities', 'Televisions & Videos', 'Digital Goods', 'Data Storage', 'Mobiles & Tablets'],
    'Entertainment': ['Gaming & Consoles', 'Media, Music & Books', 'Entertainment'],
    'Fashion & Retail': ['Fashion Accessories', 'Fashion & Retail', 'Women Shoes', 'Women Clothes', 'Men Clothes', 'Baby & Kids Fashion', 'Women Bags', 'Muslim Fashion', 'Men Bags', 'Men Shoes', "Women's Shoes and Clothing", "Men's Shoes and Clothing", "Kids' Shoes and Clothing"],
    'Health and Wellness': ['Health', 'Health and Wellness'],
    'Hobbies': ['Hobbies & Collections', 'Hobbies', 'Toys & Games'],
    'Home Improvement/Furniture': ['Home & Living', 'Home Improvement/Furniture', 'Home Appliances', 'Kitchen & Dining', 'Lighting & DÃ©cor', 'Small Appliances', 'Household Supplies', 'Bedding & Bath', 'Outdoor & Garden', 'Furniture & Organization', 'Tools & Home Improvement', 'Laundry & Cleaning Equipment', 'Large Appliances'],
    'Jewelry & Timepieces': ['Watches', 'Jewelry & Timepiece', 'Watches Sunglasses Jewellery'],
    'Miscellaneous': ['Automobiles','Miscellaneous', 'Pets', 'Mom & Baby', 'Books & Magazines', 'Stationery', 'Tickets, Vouchers & Services', 'Motorcycles', 'Free Sample (Flexi Combo)', 'Pet Supplies', 'Mother & Baby', 'Stationery, Craft & Gift Cards', 'Motors', 'Surprise Box', 'Telco', 'Stationery & Craft', 'Local Service', 'Services'],
    'Sports and Fitness': ['Sports & Outdoors', 'Sports and Fitness', 'Sports Shoes and Clothing'],
    'Supermarkets': ['Food & Beverage', 'Supermarkets','Groceries'],
    'Travel': ['Travel & Luggage', 'Travel','Bags and Travel'],
    'Retailers': ['Retailers'],
    'Marketplace': ['Marketplace'],
    'Cafe': ['Cafe'],
    'Finance and Banking': ['Finance and Banking'],
    'Department Stores': ['Department Stores'],
    'Visa Generic': ['VISA Generic'],
    'VISA Generic': ['VISA Generic'],
    'Real Estate': ['Real Estate'],
    'Restaurants': ['Restaurants']
}



# Map transaction sub-categories to offer main categories
def map_to_offer_category(sub_categories):
    offer_categories = set()
    for sub_category in sub_categories:
        for offer_category, mapped_sub_categories in category_mapping.items():
            if sub_category in mapped_sub_categories:
                offer_categories.add(offer_category)
    return list(offer_categories)

#Changed Code
# Map top categories to offer categories
def map_top_categories_to_offers(top_categories):
    offer_categories = []
    for category in top_categories:
        mapped_categories = map_to_offer_category([category])
        if mapped_categories:  # Check if the list is not empty
            offer_categories.append(mapped_categories[0])
        else: 
            print(mapped_categories, category)
    return offer_categories

# Define function to recommend offers for each offer category
def recommend_offers_for_category(offer_df, offer_category):
    # Filter offers based on the "Merchant_type" column to match the offer category
    matching_offers = offer_df[offer_df['Merchant_type'] == offer_category]
    return matching_offers

# Define function to recommend offers for each offer category
def recommend_offers_for_categories(offer_df, offer_categories):
    recommended_offers = {}
    for category in offer_categories:
        recommended_offers[category] = recommend_offers_for_category(offer_df, category)
    return recommended_offers

# Example: Print top and offer categories for a user
def print_top_and_offer_categories(merged_df, user_id, offer_df):
    top_categories = recommend_top_categories_content_based(merged_df, user_id)
    
    print(f"Top categories for user {user_id}:")
    for i, category in enumerate(top_categories, start=1):
        print(f"{i}. {category}")

    offer_categories = map_top_categories_to_offers(top_categories)

    print("\nOffer categories:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"{i}. {category}")

    recommended_offers = recommend_offers_for_categories(offer_df, offer_categories)

    print(f"\nOffers we recommend for user {user_id}:")
    for i, category in enumerate(offer_categories, start=1):
        print(f"\n{i}. {category}")
        if not recommended_offers[category].empty:
            print(recommended_offers[category][['offer_id', 'merchant_name', 'offer_title', 'Offer_amount(%)']].to_string(index=False))
        else:
            print("No offers available for this category.")

    #Changed - added list of offer ids        
    # Read the M1_offers.csv file
    offer_df = pd.read_csv("M1_offers.csv")

    # Offer IDs provided
    offer_ids = [15, 699, 627, 10, 20, 138, 21]

    # Offer categories
    offer_categories = offer_categories

    # Filter the offer DataFrame for the provided offer IDs
    filtered_offers = offer_df[offer_df['offer_id'].isin(offer_ids)]

    # Extract the relevant Merchant_type for the filtered offers
    merchant_types = filtered_offers.set_index('offer_id')['Merchant_type'].to_dict()

    # Initialize lists to store the matching and non-matching offer IDs
    matching_offer_ids = []
    non_matching_offer_ids = []

    # Match each Merchant_type with the offer categories
    for offer_category in offer_categories:
        for offer_id, merchant_type in merchant_types.items():
            if merchant_type == offer_category:
                matching_offer_ids.append(offer_id)

    # Get non-matching offer IDs
    non_matching_offer_ids = [offer_id for offer_id in offer_ids if offer_id not in matching_offer_ids]

    # Print matching offer IDs first, then non-matching ones
    print("Matching Offer IDs:", matching_offer_ids)
    print("Non-Matching Offer IDs:", non_matching_offer_ids)
    # Merge matching_offer_ids and non_matching_offer_ids
    merged_offer_ids = matching_offer_ids + non_matching_offer_ids
    print('Merged offer IDs list')
    print(merged_offer_ids)
    
                
# Example: Get top category recommendations for a user
#003d363e-5e74-4bd9-9b7f-77d1ddf0ad62 Unique Category Counts 1
#05e3cacf-ce64-488f-9f42-f8c1c0a78fd5 Unique Category Counts 22
#009caacf-c094-4b84-adde-424c584b0b33 Unique Category Counts 3
#06034ff3-ba22-4b1c-9f09-6253c35e7658 Unique Category Counts 4
#01 New User
user_id = '01'
print_top_and_offer_categories(merged_df, user_id, offer_df)