# Cashback analysis


- Merchant wise
- Month wise 
- Year wisw
- Weekend wise

## Loading data

In [2]:
import pandas as pd

# Load your dataset
df = pd.read_csv('./datasource/kavinash_req.csv')

df.head()

,Conversion ID,Advertiser,Status,Order ID,Conversion Time,Click Time,Currency,EUID,Estimate Order Value,Estimate Optimise Cashback Value,Cashback % or Amount,Estimate M1 Cashback Value,Estimate Cashback Value\n(Exclude GST),Unnamed: 13,Settlement Date,Partner Approved but payment not received. But pulseid have done the settlement
0,1011l2129173556,tripcom,pending,32904810193,11/6/2024 9:32,11/6/2024 9:21,USD,7b4ad912-c947-4dec-b725-eb695605cf3d,237.17,2.37,0.01,NaN,NaN,NaN,NaN,NaN
1,4ce2be5b098a4122b60c5959890b61dc-1,Shopee Singapore,Pending,240610NAKUEKCW_25772727027_1,10/6/2024 23:35,10/6/2024 19:13,SGD,2c495845-1dd9-41f9-8211-c626d11d3f1c,22.72,0.36,0.9,20.448,19.017,NaN,NaN,NaN
2,98d7396291e1428497d4fe2ff632a432-1,Shopee Singapore,Pending,240610N55XQBPN_24931109126_2,10/6/2024 21:58,10/6/2024 21:54,SGD,a575aea7-1438-47a5-93fe-17d735dc21f9,21.42,0.34,1.6,34.272,31.873,NaN,NaN,NaN
3,ff89a960824142ce8db6e24fac773abb-1,Shopee Singapore,Pending,240610N55XQBPN_24781116439_1,10/6/2024 21:58,10/6/2024 21:54,SGD,a575aea7-1438-47a5-93fe-17d735dc21f9,3.58,0.06,1.6,5.728,5.327,NaN,NaN,NaN
4,992fb4ca916f450fac0c3a7bf8e65709-1,Shopee Singapore,Pending,240610MCBMF93J_21684968148_1,10/6/2024 14:34,10/6/2024 14:33,SGD,a3717324-15d4-4597-8491-4d8ff2f6fd4c,3.11,0.05,0.9,2.799,2.603,NaN,NaN,NaN

## Preprocessing

In [ ]:
df['Advertiser'] = df['Advertiser'].replace('Shopee Singapore', 'Shopee SG').replace('Shopee SG - CPS', 'Shopee SG').replace('Trip.com', 'tripcom').replace('Decathlon', 'Decathlon SG')

In [3]:
df.head()

,Conversion ID,Advertiser,Status,Order ID,Conversion Time,Click Time,Currency,EUID,Estimate Order Value,Estimate Optimise Cashback Value,Cashback % or Amount,Estimate M1 Cashback Value,Estimate Cashback Value\n(Exclude GST),Unnamed: 13,Settlement Date,Partner Approved but payment not received. But pulseid have done the settlement
0,1011l2129173556,tripcom,pending,32904810193,11/6/2024 9:32,11/6/2024 9:21,USD,7b4ad912-c947-4dec-b725-eb695605cf3d,237.17,2.37,0.01,NaN,NaN,NaN,NaN,NaN
1,4ce2be5b098a4122b60c5959890b61dc-1,Shopee Singapore,Pending,240610NAKUEKCW_25772727027_1,10/6/2024 23:35,10/6/2024 19:13,SGD,2c495845-1dd9-41f9-8211-c626d11d3f1c,22.72,0.36,0.9,20.448,19.017,NaN,NaN,NaN
2,98d7396291e1428497d4fe2ff632a432-1,Shopee Singapore,Pending,240610N55XQBPN_24931109126_2,10/6/2024 21:58,10/6/2024 21:54,SGD,a575aea7-1438-47a5-93fe-17d735dc21f9,21.42,0.34,1.6,34.272,31.873,NaN,NaN,NaN
3,ff89a960824142ce8db6e24fac773abb-1,Shopee Singapore,Pending,240610N55XQBPN_24781116439_1,10/6/2024 21:58,10/6/2024 21:54,SGD,a575aea7-1438-47a5-93fe-17d735dc21f9,3.58,0.06,1.6,5.728,5.327,NaN,NaN,NaN
4,992fb4ca916f450fac0c3a7bf8e65709-1,Shopee Singapore,Pending,240610MCBMF93J_21684968148_1,10/6/2024 14:34,10/6/2024 14:33,SGD,a3717324-15d4-4597-8491-4d8ff2f6fd4c,3.11,0.05,0.9,2.799,2.603,NaN,NaN,NaN

### Only using required Cols

In [4]:
required_cols = ['Conversion ID', 'Advertiser', 'Status', 'Conversion Time','Estimate M1 Cashback Value' ]
df = df[required_cols]

### Handling null values

In [5]:
df.isnull().sum()

Conversion ID                 1
Advertiser                    0
Status                        0
Conversion Time               0
Estimate M1 Cashback Value    2
dtype: int64

In [6]:

df = df.dropna()

## Saving Processed dataset

In [8]:
df.to_csv('./datasource/preprocessed_data.csv', index=False)