### Installing dependencies

In [4]:
import os
import requests
import sys
import warnings
warnings.filterwarnings("ignore")

def download_data(spreadsheet_id, gid, outDir, outFile):
    url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=csv&gid={gid}'
    response = requests.get(url)
    if response.status_code == 200:
        filepath = os.path.join(outDir, outFile)
        with open(filepath, 'wb') as f:
            f.write(response.content)
            print('CSV file saved to: {}'.format(filepath))    
    else:
        print(f'Error downloading Google Sheet: {response.status_code}')
        sys.exit(1)

##############################################

outDir = 'm1 latest/'

os.makedirs(outDir, exist_ok=True)
filepath = download_data('1ukEyZGCFip3X0WlnS_FBCrKxwqlO-n5q', '592963761', outDir, "devnodes.csv")

sys.exit(0)

CSV file saved to: m1 latest/devnodes.csv

SystemExit: 0

In [1]:
import os
import requests
import sys
import warnings
warnings.filterwarnings("ignore")

def download_data(spreadsheet_id, gid, outDir, outFile):
    url = f'https://docs.google.com/spreadsheets/d/{spreadsheet_id}/export?format=csv&gid={gid}'
    response = requests.get(url)
    if response.status_code == 200:
        filepath = os.path.join(outDir, outFile)
        with open(filepath, 'wb') as f:
            f.write(response.content)
            print('CSV file saved to: {}'.format(filepath))    
    else:
        print(f'Error downloading Google Sheet: {response.status_code}')
        sys.exit(1)

##############################################

outDir = 'm1 latest/'

os.makedirs(outDir, exist_ok=True)
filepath = download_data('1Om2ujBGwCV3XZCY69-qi_e63bByuyjs4', '592963761', outDir, "devnodes.csv")

sys.exit(0)

CSV file saved to: m1 latest/devnodes.csv

SystemExit: 0

In [13]:
def load_data(csv_file, year):
    import pandas as pd
    # Load whole data set and filtering calender year data
    df = pd.read_csv(csv_file)
    # Convert the 'Conversion Time' column to datetime
    df['Conversion Time'] = pd.to_datetime(df['Conversion Time'], format='%d/%m/%Y %H:%M')
    
    # Filter the rows where the year is the input year and the Conversion Time is before the current date
    df = df[(df['Conversion Time'].dt.year == year) ]
    return df

df = load_data('m1 latest/devnodes.csv', 2024)

In [16]:
from dateutil import parser
from datetime import datetime

# Assuming df is your DataFrame and 'Conversion Time' is your column with dates
dates = df['Conversion Time']

def preprocess_dates(date_list):
    processed_dates = []
    for date in date_list:
        try:
            # Convert date to string
            date_str = str(date)
            # Try to parse the date assuming day-first format
            date_obj = parser.parse(date_str, dayfirst=True)
            # Reformat to the desired format
            correct_format = date_obj.strftime("%d-%m-%Y")
            processed_dates.append(correct_format)
        except ValueError:
            # Handle the error if parsing fails
            print(f"Error parsing date: {date_str}")
            processed_dates.append(date_str)
    return processed_dates

# Preprocess the dates
processed_dates = preprocess_dates(dates)

# Add the processed dates back to the DataFrame
df['Processed Conversion Time'] = processed_dates

# Print the DataFrame with the processed dates
print(df[['Conversion Time', 'Processed Conversion Time']])

         Conversion Time Processed Conversion Time
0    2024-04-13 04:02:00                13-04-2024
1    2024-04-13 04:02:00                13-04-2024
2    2024-04-13 04:02:00                13-04-2024
3    2024-12-04 20:57:00                12-04-2024
4    2024-12-04 20:33:00                12-04-2024
...                  ...                       ...
2564 2024-01-01 11:49:00                01-01-2024
2640 2024-01-01 10:12:00                01-01-2024
2641 2024-01-01 10:12:00                01-01-2024
2642 2024-01-01 08:37:00                01-01-2024
3516 2024-04-15 17:44:00                15-04-2024

[2524 rows x 2 columns]

In [18]:
# new_user = first time user in may first transaction 
#     - no transaction in lifetime till 2021 - current year
#     - new user may only. because so many frequency . 
#     - check the first transaction happened when. 
    
# active users -

#     - may user  and previous month user
#     - 60 -  30 and frequency 1 
#     - done transaction in last and previous month
    
# before 60 dayus
#  - not active for last 60 days
 
# before 120 dayus
#  - not active for last 120 days

,Conversion ID,Advertiser,Status,Order ID,Conversion Time,Click Time,Currency,EUID,Estimate Order Value,Estimate Optimise Cashback Value,Cashback % or Amount,Estimate M1 Cashback Value,Estimate Cashback Value\n(Exclude GST),,Settlement Date,Partner Approved but payment not received. But pulseid have done the settlement,Processed Conversion Time
3,cf86acb687da4840a90354630870b651-1,Shopee SG,Pending,240412J6U1DMMX_19684223859_1,2024-12-04 20:57:00,04/12/2024 20:54,SGD,bd62c2f0-929b-48d6-891a-e9c210c68b10,29.36,0.68,1.60%,0.470,0.437,NaN,NaN,NaN,12-04-2024
4,c2587a626efc4fd4a36e7f725e37a70b-1,Shopee SG,Pending,240412J5G27R82_24872442510_1,2024-12-04 20:33:00,04/12/2024 20:32,SGD,a575aea7-1438-47a5-93fe-17d735dc21f9,39.05,0.90,1.60%,0.625,0.581,NaN,NaN,NaN,12-04-2024
5,9222f5a610524c2bb03201c54cd9e51f-1,Shopee SG,Pending,240412J4CWW77S_16607128003_1,2024-12-04 20:13:00,04/12/2024 20:10,SGD,b7bb0e0b-c997-4af5-9555-2c29cee5d9a9,18.95,0.44,1.60%,0.303,0.282,NaN,NaN,NaN,12-04-2024
6,490557b541a343e496c09d30fcf1ebb0-1,Shopee SG,Pending,240412J4CWW77S_23189763728_3,2024-12-04 20:13:00,04/12/2024 20:10,SGD,b7bb0e0b-c997-4af5-9555-2c29cee5d9a9,13.12,0.30,1.60%,0.210,0.195,NaN,NaN,NaN,12-04-2024
7,770ee56257674ed1b4cbfcb9c977b06f-1,Shopee SG,Pending,240412J4CWW77S_16607128003_2,2024-12-04 20:13:00,04/12/2024 20:10,SGD,b7bb0e0b-c997-4af5-9555-2c29cee5d9a9,7.29,0.17,1.60%,0.117,0.108,NaN,NaN,NaN,12-04-2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1673,76eca1f0a85d422480fd0a3e202b3fff-1,Shopee SG,Pending,2404061XF7KM9V_10902176740_2,2024-06-04 09:44:00,04/03/2024 16:50,SGD,be887d62-6ff8-4698-bfcc-02df525dc269,1.73,0.04,1.60%,0.028,0.026,NaN,NaN,NaN,06-04-2024
1674,0dd158c6b055442a91708139cb0a8cb4-1,Shopee SG,Pending,2404061XF7KM9V_14410687608_3,2024-06-04 09:44:00,04/03/2024 16:50,SGD,be887d62-6ff8-4698-bfcc-02df525dc269,25.45,0.59,1.60%,0.407,0.379,NaN,NaN,NaN,06-04-2024
1676,b5f2f28aaf4c4267933f599a97d2f084-1,Shopee SG,Pending,2404062D3AXVHE_24818025280_1,2024-06-04 14:06:00,04/03/2024 12:52,SGD,faace62b-fbbd-4092-83e4-728528a6ecae,19.22,0.44,1.60%,0.308,0.286,NaN,NaN,NaN,06-04-2024
1945,438ca706f08d400b90e63069a7d58669-1,Shopee SG,Pending,2404073F8CVDNV_21584629347_2,2024-07-04 00:17:00,04/02/2024 10:14,SGD,ba640a2d-b4ba-4e6e-a4af-1e41e93215f1,4.38,0.10,1.60%,0.070,0.065,NaN,NaN,NaN,07-04-2024
1946,1636ebc033934f6b88114b3c4a020f4e-1,Shopee SG,Pending,2404073F8CVDNV_21584629347_1,2024-07-04 00:17:00,04/02/2024 10:14,SGD,ba640a2d-b4ba-4e6e-a4af-1e41e93215f1,3.83,0.09,1.60%,0.061,0.057,NaN,NaN,NaN,07-04-2024

In [1]:
df.shape

NameError: name 'df' is not defined

In [153]:
df.isna().sum()

Conversion ID                                                                         0
Advertiser                                                                            0
Status                                                                                0
Order ID                                                                              0
Conversion Time                                                                       0
Click Time                                                                            0
Currency                                                                              0
EUID                                                                                  0
Estimate Order Value                                                                  0
Estimate Optimise Cashback Value                                                      0
Cashback % or Amount                                                                  0
Estimate M1 Cashback Value                                                            0
Estimate Cashback Value\n(Exclude GST)                                                0
                                                                                   2398
Settlement Date                                                                    2312
Partner Approved but payment not received. But pulseid have done the settlement    2398
dtype: int64

## Grouping 2

In [4]:
# loading

data = load_data('m1 latest/devnodes.csv', 2024)
data.shape

(2398, 16)

In [ ]:
data.columns

In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

# Load your data into the 'data' DataFrame
# data = pd.read_csv('your_data_file.csv')  # Example of loading data

# Convert the 'Conversion Time' column to datetime format
data['Conversion Time'] = pd.to_datetime(data['Conversion Time'])

# Define the current time
current_time = datetime.now()

# Create a dataframe to track user activity
user_activity = data.groupby('EUID')['Conversion Time'].agg(['min', 'max', 'count']).reset_index()
user_activity.columns = ['EUID', 'First Conversion Time', 'Last Conversion Time', 'Frequency']

# Calculate Recency (in days)
user_activity['Recency'] = (current_time - user_activity['Last Conversion Time']).dt.days

# Define the categorization logic
def categorize_user(row, current_time):
    if row['Frequency'] == 1 and row['Recency'] <= 60:
        return 'A'  # New User
    elif row['Recency'] <= 60:
        return 'B'  # Active User
    elif row['Recency'] > 120:
        return 'D'  # Not Active for Past 120 Days
    elif row['Recency'] > 60:
        return 'C'  # Not Active for Past 60 Days
    else:
        return 'Other'

# Apply the categorization
user_activity['Label'] = user_activity.apply(categorize_user, axis=1, current_time=current_time)

# user_labels = user_activity[['EUID', 'Last Conversion Time', 'Frequency', 'Recency',  'Label']]
user_labels = user_activity[['EUID', 'Last Conversion Time',  'Label']]

# Display the updated dataframe with EUID and labels
user_labels.head()

NameError: name 'data' is not defined

In [7]:
user_labels.to_csv('m1_report.csv', index=False)

In [6]:
user_labels["Label"].value_counts()

Label
A    237
B    150
C     84
D     64
Name: count, dtype: int64

In [10]:
A_label_customers = user_labels[user_labels["Label"] == 'A']
A_label_customers

                                     EUID Last Conversion Time Label
0    00112248-0f9e-49a6-99fd-d925304aeb0b  2024-05-07 21:52:00     A
2    01646e94-cf31-4762-af46-ad2396bef1e2  2024-05-13 11:56:00     A
3    02246744-16ce-4a9d-af54-e62ca1ff84b8  2024-05-13 10:24:00     A
10   042163c0-38d0-4497-b58b-e0203dd1ee03  2024-05-04 10:58:00     A
31   0fba5ea1-6241-49e5-869c-6ee65e5d005f  2024-05-04 11:48:00     A
32   10aeacb8-ede8-480e-8f59-0396bad1f727  2024-05-12 15:49:00     A
39   13d904ae-e862-4593-8a63-b77c6b81fd8a  2024-05-28 02:20:00     A
42   1452c79f-a280-453b-9993-b702793b8af4  2024-05-15 17:39:00     A
46   161be3fb-0824-4262-ba54-0834facbc24c  2024-05-05 00:17:00     A
50   17b3071c-ea5a-4dc1-8607-a818cae81a08  2024-05-11 19:40:00     A
79   2248bbdd-615e-4877-9de5-d4d8b0ba182e  2024-05-01 14:53:00     A
81   23a1065a-d78f-4e2e-bb70-c780bc08ae89  2024-05-24 21:56:00     A
89   27673348-a387-417a-a2fe-c3eedbd080ba  2024-05-24 20:29:00     A
104  2f116027-2896-4660-8682-92a45ba6146f  2024-05-14 10:00:00     A
107  31c0305c-ebcd-4384-b325-8539e99c21af  2024-05-25 02:25:00     A
114  34213221-7ee3-4a08-8e76-856ddf353bb5  2024-05-08 06:21:00     A
133  3e9ee950-996d-424e-865e-df59eeebfe5a  2024-05-20 17:01:00     A
138  3fddd01f-bea7-4137-8f2e-3172426d3f86  2024-05-17 01:16:00     A
161  4be2e898-59c7-4342-883d-ae3b8f3b5f5e  2024-05-04 12:56:00     A
164  4c663c17-7a20-4769-9a7c-c4cc312417d2  2024-05-17 07:39:00     A
166  4d352e74-0de4-4f60-96e6-7191631076b7  2024-05-28 22:21:00     A
187  55d5c3f2-01b9-4a2d-b1fb-9c82ca8e9e2c  2024-05-11 03:22:00     A
197  5a04a362-bb53-4735-a560-d2dafa6d4064  2024-05-11 14:10:00     A
198  5a4373bf-007a-466b-aee7-7e5c88a78207  2024-05-25 08:33:00     A
220  619c9925-a78c-493f-915b-a309056eb43c  2024-05-25 21:07:00     A
237  6817e9bc-0474-4c70-a8fb-cd83c8dda100  2024-05-07 16:15:00     A
246  6c542292-28c3-4911-b120-91cc9a2c56f4  2024-05-04 13:14:00     A
252  6ef17915-038f-4521-980f-939485b9977c  2024-05-08 09:45:00     A
255  6fdfd4c8-e7dd-4b9b-95c0-cc7797773222  2024-05-18 22:56:00     A
257  703e7a34-cd2c-409c-9d2c-6deb7a136c4b  2024-05-16 22:51:00     A
268  73360452-f713-49e5-b571-f9d275650915  2024-05-14 02:04:00     A
272  76d6e556-0867-41a4-b1fb-f23d21cefff4  2024-05-15 21:54:00     A
274  77f5e55d-444e-43df-a342-9a4b727bd65a  2024-05-11 18:20:00     A
279  7a999520-2971-4341-a80c-6d6d865da90a  2024-05-04 10:28:00     A
290  7fabd629-f1fd-4494-b69b-af6dff3253a8  2024-05-20 06:46:00     A
292  80e53b2a-6bed-44d2-9864-b9e99e8c6223  2024-05-17 11:41:00     A
301  86013f26-599c-4d49-9bee-2448f327bfb1  2024-05-07 03:05:00     A
306  8700f987-2b51-4658-b2c1-6577c7cd8bb1  2024-05-18 20:53:00     A
314  8b7ae5bb-37ac-4048-b3fc-4f395098931a  2024-05-25 13:44:00     A
326  904d9ed9-92cf-4bb0-9093-d418183e4cac  2024-05-05 14:29:00     A
359  a28b562f-ed36-4454-b956-6a5ffa4d7092  2024-05-06 00:08:00     A
376  a99c82e0-17ef-4b1f-880a-3d7c9b0b68b8  2024-05-14 22:10:00     A
382  acfc17dd-d579-4d2b-a644-d5bf1e523890  2024-05-05 13:20:00     A
383  ad81d15e-9193-4159-85e6-a25d7ad05b23  2024-05-16 21:03:00     A
454  d34f5baa-62b6-4add-a3e6-8563668a6156  2024-05-16 03:34:00     A
466  d9cf7a50-125b-4891-848b-6b4ba28379e2  2024-05-25 19:12:00     A
484  eae02dc5-f4f7-4673-9348-047fd1bc90cc  2024-05-04 22:11:00     A
497  f0286f8a-bac5-4c9e-b06d-cc6218a4851c  2024-05-23 09:25:00     A
505  f3ef0436-824e-4059-9da1-e0a85d3fa3f1  2024-05-11 15:12:00     A
516  f87a2e42-88a1-4ce3-a829-a796b45da482  2024-05-04 20:09:00     A
525  fc6674ab-8351-452a-ad92-f1bebd721b98  2024-05-27 13:01:00     A

In [164]:
B_label_customers = user_labels[user_labels["Label"] == 'B']
B_label_customers

,EUID,Last Conversion Time,Frequency,Recency,Label
5,02eef51b-f7ef-4211-9c0e-13ae44bbe35d,2024-05-07 20:54:00,2,22,B
27,0dd81f16-998e-49de-8d71-afde052b37d3,2024-05-10 11:11:00,4,20,B
30,0f2e4a0b-dbe1-4218-ae6e-b40620af391f,2024-05-06 08:16:00,15,24,B
34,122a2c4b-5088-420f-9369-ed152ffaff8f,2024-05-25 18:16:00,4,4,B
36,12796ff7-c2a0-40ab-83b4-190ab570fc35,2024-05-17 11:54:00,2,13,B
...,...,...,...,...,...
494,eec306f9-f708-473e-9eb7-4dc1e02d4c5e,2024-05-05 12:38:00,3,25,B
503,f2231520-82af-4ec1-9b17-b10277dd77a3,2024-05-03 10:03:00,8,27,B
511,f63e359f-8b70-4247-8d0a-f6eaf76aa873,2024-05-04 12:11:00,2,26,B
522,fa5af524-2a78-4617-b5db-5e45ae3424e8,2024-05-05 21:44:00,16,24,B
530,fd49952c-7961-41fd-ab48-712c09591fc3,2024-05-24 11:09:00,87,6,B

In [165]:
A_label_customers = user_labels[user_labels["Label"] == 'Other']
A_label_customers

,EUID,Last Conversion Time,Frequency,Recency,Label
6,02f6632d-22cc-4ac9-90c5-7f37149f4951,2024-04-24 13:50:00,21,36,Other
8,037c52ea-153a-44d1-9e3c-a67f82c8c2d0,2024-04-27 16:46:00,2,33,Other
11,0583e436-4559-4149-b5ba-09f88db13a52,2024-04-18 04:12:00,2,42,Other
18,09aaba28-e447-4de1-8280-0695a68077b1,2024-04-23 11:08:00,2,37,Other
23,0d2c9813-077d-4dac-8dd7-58ae7eabaa11,2024-04-24 14:15:00,2,36,Other
26,0d893f10-489e-4154-9928-129dde19b2f8,2024-04-25 22:39:00,3,34,Other
33,11398b24-ed20-411e-ad86-51b25dcc2404,2024-04-04 04:50:00,2,56,Other
44,15a545f3-780b-4947-8b3e-fe03686e75b6,2024-04-24 11:07:00,9,36,Other
59,19d00b3e-0f22-4c2e-8693-ddfeaf7b90e9,2024-04-15 17:44:00,4,44,Other
60,1c062987-12d3-4202-a1ad-7fd829dfd8ee,2024-04-16 13:55:00,2,44,Other
68,1ed2bd0a-5e6a-4b3a-baa5-4fe40cd33efa,2024-04-21 09:41:00,2,39,Other
69,1f1a1439-cdb5-4ef5-b9cc-ba88fb7caa67,2024-04-14 13:51:00,2,46,Other
86,261959ec-4bcb-4dfa-9b24-3cce7398baf1,2024-04-15 22:13:00,5,44,Other
87,263af0de-aaff-438a-bae5-82bbc1912438,2024-04-16 11:50:00,2,44,Other
88,2692b06c-5918-42f7-85c5-5e50cabd7961,2024-04-25 11:08:00,10,35,Other
93,28ab8589-8bea-45ee-8e38-f607e78ac4e6,2024-04-14 10:45:00,2,46,Other
101,2cb234da-dd5d-44bc-9dee-ba76c9b7249a,2024-04-21 15:21:00,3,39,Other
106,319b7f67-a402-4b13-b99f-079916fc965a,2024-04-18 13:30:00,6,42,Other
112,330b8b47-8766-4110-9d75-912b1f913205,2024-04-16 00:45:00,6,44,Other
131,3d8cdbfd-144a-48d5-a5d0-385654eba3e5,2024-04-21 08:41:00,3,39,Other
149,4521065c-85fa-4e61-af93-2c5080fb86c4,2024-04-25 15:33:00,3,35,Other
174,50c03543-5779-4ed3-9393-c2e96052563f,2024-04-21 18:38:00,2,38,Other
180,549cbbcd-e99c-419a-8980-225d7f7f1e20,2024-04-17 11:21:00,2,43,Other
209,5db29390-fff6-490c-b621-e08fd1777a5f,2024-04-21 10:38:00,2,39,Other
210,5e1d9177-5f3a-4699-8406-8e0871ccb8ca,2024-04-20 13:48:00,2,40,Other
226,6518faa7-3301-4c33-b7b3-58ba405cfaa2,2024-04-15 19:27:00,2,44,Other
236,680f07e8-b04c-4bf4-9acc-83bc57df0751,2024-04-13 19:27:00,2,46,Other
242,6a59a7a3-4749-4151-8614-099af8311ace,2024-04-28 04:04:00,12,32,Other
254,6fd0ae07-5417-4c97-8706-930b22ba408c,2024-04-23 21:38:00,6,36,Other
258,7042abc7-3ca7-4ed5-89e8-b44d7ef4c23c,2024-04-04 09:29:00,3,56,Other
287,7f1025d6-8da3-42f5-a358-8285f8a124db,2024-04-19 07:49:00,36,41,Other
295,82b7d5c0-d175-4391-bd1f-fb2199c0049e,2024-04-04 08:35:00,16,56,Other
300,852d0b7e-c1f3-4a1b-b129-9ab5af72ad81,2024-04-26 13:39:00,3,34,Other
304,86e5b756-966e-45e5-bdd7-36dedccc6bf2,2024-04-04 22:56:00,6,55,Other
322,8f2b9874-ec0d-4fbf-afc6-de59cc717159,2024-04-28 18:10:00,3,31,Other
325,8fb76e83-2565-4805-b91e-ebde7b23e5dc,2024-04-25 01:22:00,4,35,Other
334,952afb00-db8f-4b56-a29e-682a1b83c15d,2024-04-22 16:36:00,3,38,Other
343,9a9da9d0-03ff-4838-86a3-6a7f7af4f097,2024-04-04 17:58:00,4,55,Other
346,9bd44d34-74c5-41ee-8dd7-1d114a0b6320,2024-04-24 17:52:00,8,35,Other
366,a575aea7-1438-47a5-93fe-17d735dc21f9,2024-04-29 15:51:00,19,31,Other
367,a59ad586-9cc1-4c88-ba52-2aa98202afb3,2024-03-31 13:54:00,2,60,Other
375,a922795d-7e17-40d3-baaf-ef7d117c150d,2024-04-04 00:34:00,4,56,Other
401,bb21669f-a54d-4fcd-8f51-79ffb1674511,2024-04-13 22:04:00,2,46,Other
432,c8789972-c695-43c9-8e96-1889b321358b,2024-04-04 12:36:00,2,56,Other
442,cb4c722d-d774-4f40-b523-dc6faa59aee0,2024-04-04 20:03:00,10,55,Other
451,d1036feb-9268-4017-9f5a-aa72a79720d0,2024-04-19 21:34:00,3,40,Other
463,d6e90114-6781-49ac-a0b3-82a76734136b,2024-04-04 00:12:00,4,56,Other
477,e594e3d5-d1a5-41fe-b123-2ad41dc85e6b,2024-04-16 21:52:00,32,43,Other
478,e5dda5ff-ffa2-453f-8c65-5a802b395946,2024-04-27 08:02:00,2,33,Other
479,e72ef705-17b1-4bb8-9365-70a91328b6fe,2024-04-27 12:21:00,7,33,Other
492,eddcb372-8194-4094-88aa-a55ae21749f1,2024-04-18 18:23:00,2,41,Other
510,f55b5b06-fbe4-48fb-bd4b-807fff0f4702,2024-04-28 00:27:00,5,32,Other
514,f8182d61-84a7-45e5-a51b-a231b220defa,2024-04-04 00:55:00,3,56,Other

In [142]:
df["Conversion Time"].sort_values(ascending=False).loc[df["Conversion Time"] < pd.Timestamp('2024-06-01')]
# 126 records.

0      2024-05-28 22:21:00
2      2024-05-28 14:51:00
4      2024-05-28 14:51:00
1      2024-05-28 14:51:00
3      2024-05-28 14:51:00
               ...
2538   2024-01-01 10:12:00
2539   2024-01-01 09:57:00
2540   2024-01-01 08:37:00
2541   2024-01-01 00:13:00
2542   2024-01-01 00:13:00
Name: Conversion Time, Length: 2398, dtype: datetime64[ns]